### ISSUE TITLE
Map does not change once timer ends. 

### ISSUE THREAD

**Issue by jensenhuangyankai** [TotallyMehis/Influx-Timer#10]
Can someone provide me a config where the map changes every 30 mins? I cannot seem to figure out how to do it. using Bhop plugin btw. Thanks :)

**Comment by maugerb** [comment]
I think its you want : Plugin Quick Map Rotate (its for switch map when no player is in the server)
Link : [](url)https://forums.alliedmods.net/showthread.php?p=1830801

In your server.cfg
Add cvar 
- sm_qmr_enable 1
- sm_qmr_timelimit 30
- sm_qmr_player_quota 1

----------------------------------------------------------------------------------------------------------
Maybe you need to switch this on [css] /cstrike/cfg/sourcemod/rtv.cfg or [csgo] /csgo/cfg/sourcemod/rtv.cfg

Be sure you have mapchooser.smx and rtv.smx in /cstrike or csgo/addons/sourcemod/plugins/
If is not there search in /cstrike or csgo/addons/sourcemod/plugins/disabled/    and copy and paste in /cstrike or csgo/addons/sourcemod/plugins/
(the new config file is auto generated when you start the server with this plugin in the good directory)

// When to change the map after a succesful RTV: 0 - Instant, 1 - RoundEnd, 2 - MapEnd
// -
// Default: "0"
// Minimum: "0.000000"
// Maximum: "2.000000"
sm_rtv_changetime "2"

// What to do with RTV's after a mapvote has completed. 0 - Allow, success = instant change, 1 - Deny
// -
// Default: "0"
// Minimum: "0.000000"
// Maximum: "1.000000"
sm_rtv_postvoteaction "success"

------------------------------------------------------------------------------------------------

For finish go in server.cfg (cstrike or csgo/cfg/server.cfg)
mp_timelimit "30"	//How many minutes for the whole map

**Comment by TotallyMehis** [comment]
Commit 37d38dfb274eaf607a77b4e0ba985651ab9d46e8 should help you with this. You can download influx_fixtimelimit.sp and compile it locally. You do not need to update your timer version to dev version.

Please tell me if it worked.

**Comment by rambatencs** [comment]
Hi! I tried that..But didnt work for me...

**Comment by maugerb** [comment]
What is the ip of your server? I want to help you!

**Comment by rambatencs** [comment]
Add me steam: http://steamcommunity.com/id/RAMBATENN/

I manage 2 CS:GO servers..bhop and surf..

**Comment by maugerb** [comment]
try this https://forums.alliedmods.net/showthread.php?t=254830

**Comment by maugerb** [comment]
I think you need to edit mapchooser.sp to do this! Because the round never end. Need to force map switch!

**Comment by M-archand** [comment]
Having issues with mapchooser and the map changing as well on cs:go. Use to work fine but after May 2nd patch the map vote won't up at the end anymore and it hangs at 0:00, haven't changed any settings. Isn't happening in my other server using ckSurf

**Comment by TotallyMehis** [comment]
The new version of influx_fixtimelimit should fix this for good. (25e6e0adb07ce2449953f668c96a412628edcd42)
