### ISSUE TITLE
Insert mistake

### ISSUE THREAD

**Issue by ghost** [TotallyMehis/Influx-Timer#100]
I occur a strange bug, where the username is not being inserted into the database. Every entry just says "N/A". Other inserts working perfectly fine.

![bug](https://user-images.githubusercontent.com/61086216/79265575-9c423400-7e96-11ea-9411-110bd93cd6ed.PNG)

Using the latest Dev Build (_79_), as you have recommended me today.
Nothing in my error logs.

**Comment by TotallyMehis** [comment]
The player names are inserted when the player leaves the server. Are you sure this is not happening?

**Comment by ghost** [comment]
> 
> 
> The player names are inserted when the player leaves the server. Are you sure this is not happening?

Edit: Yes and no. I got 943 entries and only 34 names.

**Comment by TotallyMehis** [comment]
Player name is now added on new insert.
