### ISSUE TITLE
Glitch with !noclip

### ISSUE THREAD

**Issue by maugerb** [TotallyMehis/Influx-Timer#11]
Hi Mehis I love your project I follow you everyday. I have some cheat with !noclip on my server to fix that I need to put anti prespeed to 800! The bug is if a player bind sm_noclip and he take speed with noclip on start of the map. 

Bug
1- the player do !noclip (bind command sm_noclip)
2- the player say !practice to remove the practice session
3-the player take speed and release sm_noclip to start very fast on start

I want server without prespeed but I cant. I have too many cheater!

Can you do something to kill this cheater?
Like when you noclip off you have cooldown of 3 sec to start a run? (If practice is off)
Or when you noclip off you tele to start without speed! (If practice is off)

thx you very much I wanna help you to kill bug!

**Comment by TotallyMehis** [comment]
New commits 02d1db0c697923799c028d13cc90b93ea4385020 and 9c30d11fc143b5418a920f2c383520586cf73b21 fix the problem. You can download influx_practise and influx_noclip from Github and then compile them locally. You also need the include files.

**Comment by maugerb** [comment]
The Bug work again. I have the 1.06 with your 2 new files compiled! I can prespeed with 1500 speed.
My prespeed config file : 
- influx_prespeed_cap "1"
- influx_prespeed_max "0"
- influx_prespeed_maxjumps "0"
- influx_prespeed_usetruevel "0"

Maybe I need to upload all your dev script to work?

You can downlaod a demo of the bug here : [](url)http://paradiseclan.net/influx.rar

**Comment by TotallyMehis** [comment]
Are you sure you compiled it correctly? I cannot reproduce the problem.

**Comment by maugerb** [comment]
Im sure I recompiled to be sure. I cannot test on your test server because you set only 1 jump for starting. Im on counter strike source! my server to test : 198.50.245.166:27015 or add me on steam http://steamcommunity.com/id/mauger16

**Comment by maugerb** [comment]
Ok i got the problem lol :P When I clone downlaod your git I dont have the update for influx_noclip.sp  :)
I just copy and paste and compile sorry :P

**Comment by maugerb** [comment]
Your the men! Great Work
Scripter A++++
I make a donation!

---Solved---
