### ISSUE TITLE
All Chat!

### ISSUE THREAD

**Issue by maugerb** [TotallyMehis/Influx-Timer#12]
Do you have a All chat plugin for Counter Strike Source. (spec can chat with alive player) Because in csgo the game already have cvar for this.

**Comment by coffee12** [comment]
its sv_full_alltalk 1 I'm pretty sure but make sure u have sv_deadtalk 1 and sv_alltalk 1

**Comment by maugerb** [comment]
Unknown command for counter strike source! This is cvar for csgo only! sv_alltalk 1 is already On but its only for vocal chat.

**Comment by maugerb** [comment]
Your plugin work! Thx I donate again!

--Solved--

**Comment by TotallyMehis** [comment]
Great to hear that it worked! (ef5688fefe6447c86f99a9792ba3ffa4853b7ca3)

**Comment by maugerb** [comment]
Not tested on csgo!
