### ISSUE TITLE
Not getting full jump at start.

### ISSUE THREAD

**Issue by Some1sm** [TotallyMehis/Influx-Timer#15]
If you jump just at the edge of a start zone you will have half jump heigh and your speed will be reduces to 190-200 speed max.
https://www.youtube.com/watch?v=E0_WtVjF6Ik

**Comment by M-archand** [comment]
Make sure to check your `influx_prespeed_max` (cfg/influx/prespeed.cfg) that it isn't at 200 or something

**Comment by TotallyMehis** [comment]
https://influxtimer.com/download#faq
