### ISSUE TITLE
Unable to switch weapons

### ISSUE THREAD

**Issue by M-archand** [TotallyMehis/Influx-Timer#16]
Can't seem to switch between weapons with the number keys, only scroll wheel. Is this intentional? I looked through the plugin list and configs and couldn't seem to find anything.

**Comment by maugerb** [comment]
On counter strike source work number 1 for me. But I use number on keyboard ... not the number where the number lock is. Watch if your bind is ok !

**Comment by M-archand** [comment]
Should of also mentioned this is for cs:go. Also talking about the numbers above qwerty of course. It's not my weapon binds, they work elsewhere. Tested this on 3 different computers with different accounts.

**Comment by TotallyMehis** [comment]
It has something to do with the panel hud sidebar. I may recreate the hud one day to fix it.

**Comment by M-archand** [comment]
Thanks, hope this is something that you might consider doing soon. I really do like Influx but I feel like being not being to switch weapons if you use scroll wheel to jump is pretty detrimental.

~~Another quick question, more about Sourcemod in general rather than Influx but... how do I change the Influx chat tag?  Like where it says [INFLUX] before a message, I'd like to change the color from orchid/purple, and maybe shorten to [INF.] or something smaller~~ *nvm I see it in the core.cfg

**Comment by TotallyMehis** [comment]
This is now fixed for good.
