### ISSUE TITLE
Timer plugin can't work in new sourcemod and metamod

### ISSUE THREAD

**Issue by zzzznn5000** [TotallyMehis/Influx-Timer#17]
Because CSGO's new update,I install new sourcemod and metamod,but the Timer plugin have some problems, one is when you leave start zone,your time will not start and appear " [Influx] You do not have a trikz buddy! (!buddy) " in chat window,another problem is map can't load zone,when you type in !zone and select create zone,you can't see later menu completely,just can see sequence numbers.

**Comment by maugerb** [comment]
I use  SourceMod (1.8.0.5951) work number one! 

Windows : https://sm.alliedmods.net/smdrop/1.8/sourcemod-1.8.0-git5951-windows.zip
Linux : https://sm.alliedmods.net/smdrop/1.8/sourcemod-1.8.0-git5951-linux.tar.gz

Use the lastest matamod

**Comment by TotallyMehis** [comment]
Don't use influx_trikz-plugin.
