### ISSUE TITLE
CSGO prestrafe

### ISSUE THREAD

**Issue by e-slut** [TotallyMehis/Influx-Timer#19]
There is no prestrafing in CSGO and it would be nice to see a prestrafe plugin.

**Comment by coffee12** [comment]
There is a prestrafe plugin

**Comment by coffee12** [comment]
It's csgo movement unlocker

**Comment by e-slut** [comment]
Tried that doesn't work.

**Comment by e-slut** [comment]
I forgot to put the .txt in the gamedata folder I'm stupid
