### ISSUE TITLE
Own replay

### ISSUE THREAD

**Issue by nknm** [TotallyMehis/Influx-Timer#22]
I've been asking myself if the "own replay" feature was broken but recently i figured it out, it replays your last try at the map, even if you don't finish, as long as you leave the start-zone and start hopping it starts recording your own replay, and when u reset it stops, you don't have to finish the map nor have your best time for it to record, I don't know if that's what was intended for this feature.
I started noticing something weird when I just joined the map that I've finished a lot of times and the own replay was grey (Locked/unable to select). And then i tried to understand it from there, i tried to just do 3 jumps and reset, spec the bot, play my own replay, and that was my own replay, those 3 jumps.
Probably this is what you wanted to do with this feature because if you actually save everyone's best time after a long time if 100 people play every map being ~~ 1000 maps i'd do be 10000 replays that way it doesn't save but also deletes your replay if you just leave the start-zone, my suggestion is to save it while the map is being played but only if you finished the map / your best run.

**Comment by TotallyMehis** [comment]
The feature does work as intended.

As for the request; it's simply not worth the trouble. If you accidentally overwrite your replay, it's only a mild annoyance.
