### ISSUE TITLE
Timer doesn't start

### ISSUE THREAD

**Issue by Rostu13** [TotallyMehis/Influx-Timer#24]
Hello. Just set the timer and there was a problem. When I exit the start zone, the timer does not go. The chat says "fps_max".
![20170606110132_1](https://cloud.githubusercontent.com/assets/22251516/26814240/61d3e210-4ac7-11e7-999f-ea6ffd97d2c6.jpg)
![20170606110135_1](https://cloud.githubusercontent.com/assets/22251516/26814241/61d7d47e-4ac7-11e7-87c9-5abd96d19da3.jpg)

**Comment by TotallyMehis** [comment]
Are there any errors? I've encountered this problem before but I can't put my finger on what caused it.

**Comment by Rostu13** [comment]
I do not understand too. It started after the server was reinstalled. But the new server is completely copied from the old one. There are no errors. I thought that with the installation of the problem, but no.

**Comment by TotallyMehis** [comment]
Post the list of plugins you are using (sm plugins list)

**Comment by Rostu13** [comment]
I didn't clean the css plugins.

   01 "Influx - No Collision" (1.0.7) by Mehis
  02 "Influx - Practice" (1.0.7) by Mehis
  03 "Timeleft Round End" (2.0.0) by AlmazON
  04 "Influx - Hide Players | Weapon Sounds" (1.0.7) by Mehis
  05 "Token Auto Updater" (1.3.1) by ˙·٠●Феникс●٠·˙
  06 "Influx - Zones | Stage" (1.0.7) by Mehis
  07 "Admin File Reader" (1.8.0.6002) by AlliedModders LLC
  08 "MPBH" (1.0) by DaFox, petsku & Zipcore
  09 "Terrible No After Bots" (0.02) by Sheepdude
 10 "Influx - HUD" (1.0.7) by Mehis
  11 "Manual Cleaning Map" (1.0.3) by AlmazON
  12 "Influx - HUD | Chat Records" (1.0.7) by Mehis
  13 "Influx - Help" (1.0.7) by Mehis
  14 "Client Preferences" (1.8.0.6002) by AlliedModders LLC
  15 "Influx - Record Rank" (1.0.7) by Mehis
  16 "SourceComms" (0.9.262) by Alex
  17 "Influx - Prespeed" (1.0.7) by Mehis
  18 "Influx - Teams" (1.0.7) by Mehis
  19 "Influx - Teleport to end" (1.0.7) by Mehis
  20 "Influx - Style - Half-Sideways" (1.0.7) by Mehis
  21 "Influx - Give Weapons" (1.0.7) by Mehis
  22 "Influx - Zones | Teleport" (1.0.7) by Mehis
  23 "Influx - Zones | Freestyle" (1.0.7) by Mehis
  24 "Influx - HUD | Draw CS:GO" (1.0.7) by Mehis
  25 "Influx - Fix Timelimit" (1.0.7) by Mehis
  26 "[ Menu Creator ]" (3.0.0.1) by AlexTheRegent
  27 "Influx - Print CP Times" (1.0.7) by Mehis
  28 "Influx - Mode - Scroll" (1.0.7) by Mehis
  29 "Dynamic" (0.0.22) by Neuro Toxin
  30 "bknopka.smx"
  31 "Basic Info Triggers" (1.8.0.6002) by AlliedModders LLC
  32 "Plugin Manager" (1.1.0) by R-Hehl
  33 "[PLGN] Реклама" (1.2) by Pheonix (˙·٠●Феникс●٠·˙)
  34 "CSGO Admin Weapon Menu" (1.0.0) by Glefs
  35 "Influx - Mode - Auto" (1.0.7) by Mehis
  36 "Anti-Flood" (1.8.0.6002) by AlliedModders LLC
  37 "Influx - Zones | Checkpoint" (1.0.7) by Mehis
  38 "CS:GO Movement Unlocker" (1.0) by Peace-Maker
  39 "Influx - Zones | Block" (1.0.7) by Mehis
  40 <Failed> "Influx - Compatibility | Standup" (1.0.6) by Mehis
  41 "Admin Rock The Vote" (v1.0) by ruskydubl [vk.com/lolexe]
  42 <Failed> "Influx - Mode - Auto" (1.0.7) by Mehis
  43 "Influx - Weapon Drop" (1.0.7) by Mehis
  44 "c_hideradar.smx"
  45 "Fun Votes" (1.8.0.6002) by AlliedModders LLC
  46 "Influx - Style - Backwards" (1.0.7) by Mehis
  47 "Basic Chat" (1.8.0.6002) by AlliedModders LLC
  48 <Failed> "Influx - Drop Knife" (1.0.7) by Mehis
  49 "Security Entity Limit!" (0.5.4) by Benoist3012
  50 "Influx - Chat Records" (1.0.7) by Mehis
  51 "Influx - Beams | Default Settings" (1.0.7) by Mehis
  52 "Influx - Mode - VelCap" (1.0.7) by Mehis
  53 "Influx - Recording" (1.0.7) by Mehis
  54 "Influx - HUD | Record Sounds" (1.0.7) by Mehis
  55 "Folder View" (1.0) by wS / Schmidt
  56 "Trigger_push Fix" (1.2) by Mev, George, & Blacky
  57 "Basic Comm Control" (1.8.0.6002) by AlliedModders LLC
  58 "Influx - Style - Normal" (1.0.7) by Mehis
  59 "Sound Commands" (1.8.0.6002) by AlliedModders LLC
  60 "Influx - Strafes" (1.0.7) by Mehis
  61 "Influx - Style - Low Gravity" (1.0.7) by Mehis
  62 "Player Cleaner" (1.0.1) by White Wolf (HLModders LLC)
  63 <Failed> "Influx - HUD | Draw CSS" (1.0.7) by Mehis
  64 "Fun Commands" (1.8.0.6002) by AlliedModders LLC
  65 "Influx - Style - A/D-Only" (1.0.7) by Mehis
  66 "Influx - HUD | Viewmodel" (1.0.7) by Mehis
  67 "Influx - True Velocity" (1.0.7) by Mehis
  68 "SM First Person View Models Interface" (3.1) by Franc1sco franug
  69 "Influx - Pause" (1.0.7) by Mehis
  70 "Basic Votes" (1.8.0.6002) by AlliedModders LLC
  71 "[bTimes] - Extend" by 88
  72 "Influx - Core" (1.0.7) by Mehis
  73 "Terrible Enable Full Alltalk" (0.02) by Sheepdude
  74 "Influx - HUD Draw" (1.0.7) by Mehis
  75 "Influx - Style - W-Only" (1.0.7) by Mehis
  76 "Influx - Style - Real Half-Sideways" (1.0.7) by Mehis
  77 "SM Advanced Teleport" (1.0) by LightningZLaser
  78 "Influx - Style - Sideways" (1.0.7) by Mehis
  79 "Admin Menu" (1.8.0.6002) by AlliedModders LLC
  80 "Influx - Autojoin Team" (1.0.7) by Mehis
  81 <Failed> "Influx - Spectator All Talk (CSS)" (1.0.7) by Mehis
  82 "Influx - Config" (1.0.7) by Mehis
  83 "Influx - Trikz" (1.0.7) by Mehis
  84 "Influx - Spectator List" (1.0.7) by Mehis
  85 "Influx - Mode - Stock Cap" (1.0.7) by Mehis
  86 "Influx - Style - Parkour" (1.0.7) by Mehis
  87 "Influx - Zones | Timer" (1.0.7) by Mehis
  88 "Nextmap" (1.8.0.6002) by AlliedModders LLC
  89 "Influx - No Damage" (1.0.7) by Mehis
  90 "Stop Map Music" (1.0.0) by GoD-Tony [Fixed by The Count]
  91 "Player Commands" (1.8.0.6002) by AlliedModders LLC
  92 "Admin Help" (1.8.0.6002) by AlliedModders LLC
  93 "Fix angles" (1.0.1) by Grey83
  94 "Anti-Micspam" (0.5) by FLOOR_MASTER and Bor3dGaming.com
  95 "Influx - Map Rankings" (1.0.7) by Mehis
  96 "Influx - Disable Suicide" (1.0.7) by Mehis
  97 "Mirror" (1.0) by Franc1sco franug and Nanochip
  98 "[VIP] Test" (1.0.3) by R1KO (skype: vova.andrienko1)
  99 "[VIP] Keys" (1.0.2) by R1KO (skype: vova.andrienko1)
  100 <Failed> "[VIP] KNIFE" (1.1) by Pheonix (˙·٠●Феникс●٠·˙)
  101 "[VIP] CHAT (+scp)" (3.1.1) by R1KO
  102 "[VIP] Electro Effects" (1.0.2) by R1KO & acik
  103 "[VIP] Core" (2.1.1 R) by R1KO (skype: vova.andrienko1)
  104 "[VIP] Stats (SteamWorks)" (1.0) by R1KO & White Wolf
  105 "[VIP] COIN" (1.1.0) by Pheonix (˙·٠●Феникс●٠·˙) & R1KO
  106 "[VIP] Paticles AURA" (2.0.1) by R1KO
  107 "[VIP] NEON (CSS/CSGO)" (1.0.3) by R1KO & Pheonix (˙·٠●Феникс●٠·˙)
  108 "[VIP] Admin Privileges" (1.0.2) by R1KO (skype: vova.andrienko1)
  109 "[VIP] Skins" (1.0.5) by R1KO (skype: vova.andrienko1)
  110 "[VIP] Gravity" (1.0.0) by R1KO (skype: vova.andrienko1)
  111 "[VIP] Paint" (1.2) by Unknown & White Wolf (dead fix)
  112 "endmap_fix.smx"
  113 "sm_allinfo" (2.1.1) by {7~11} TROLL
  114 "b_maxvel.smx"
  115 "Slope Landing Fix" (1.2) by Mev & Blacky
  116 "Influx - Block +left/+right" (1.0.7) by Mehis
  117 "Influx - Zones" (1.0.7) by Mehis
  118 "Basic Commands" (1.8.0.6002) by AlliedModders LLC
  119 "Influx - Noclip" (1.0.7) by Mehis
  120 "Influx - Zones | Beams" (1.0.7) by Mehis
  121 "Clean Chat" (1.1) by Monomizer
  122 "Offline Ban list" (2.4.6) by Grey™ & R1KO
  123 "SourceBans" (1.4.10) by SourceBans Development Team
  124 "Influx - Record Sounds" (1.0.7) by Mehis
  125 "Influx - Jumps" (1.0.7) by Mehis
  126 "MapCount HostName" (1.0) by CrazyHackGUT aka Kruzefag
  127 "bTimes-ssj.smx"
  128 "Influx - Disable Radio" (1.0.7) by Mehis
  129 "Influx - HUD | Hide HUD" (1.0.7) by Mehis
  130 "Influx - HUD | Hide Players" (1.0.7) by Mehis
  131 "Influx - Style - TAS" (1.0.7) by Mehis
  132 "Influx - FPS Check" (1.0.7) by Mehis
  133 "Thirdperson" (1.6 CS:GO edition) by shavit and Franc1sco franug
  134 "Influx - Button | Timer" (1.0.7) by Mehis

**Comment by TotallyMehis** [comment]
Is there a reason why influx_trikz is loaded? Since you need a buddy (!buddy) to start the timer.

**Comment by Rostu13** [comment]
Thanks in advance. I'm sure that it will work !!!
