### ISSUE TITLE
Unable to load influx_comp_standup

### ISSUE THREAD

**Issue by InSelfControll** [TotallyMehis/Influx-Timer#26]
L 06/07/2017 - 16:18:28: [SM] Unable to load plugin "influx_comp_standup.smx": Could not find required plugin "standup_core"
How can I fix it?
BTW after I added the plugin my server stuck on cmdrate 0.0 and none can move.
No errors :(
How can I fix it?

 SourceMod Version Information:

    SourceMod Version: 1.8.0.6002

    SourcePawn Engine: SourcePawn 1.8, jit-x86 (build 1.8.0.6002)

    SourcePawn API: v1 = 4, v2 = 11

    Compiled on: Jun  2 2017 05:38:25

    Built from: https://github.com/alliedmodders/sourcemod/commit/1387257

    Build ID: 6002:1387257

    http://www.sourcemod.net/

Metamod:Source version 1.10.7-dev

Built from: https://github.com/alliedmodders/metamod-source/commit/4403e81

Build ID: 957:4403e81

Loaded As: Valve Server Plugin

Compiled on: Apr 30 2017

Plugin interface version: 15:14

SourceHook version: 5:5

http://www.metamodsource.net/

**Comment by TotallyMehis** [comment]
That's not an error that you need to be alarmed about. If you're not using Standup, you can safely ignore it.

**Comment by InSelfControll** [comment]
BTW after I added the plugin my server stuck on cmdrate 0.0 and none can move.
No errors :(
How can I fix it?
