### ISSUE TITLE
Influx is really hard

### ISSUE THREAD

**Issue by nknm** [TotallyMehis/Influx-Timer#28]
I've been playing a lot lately on your timer, influx, and its has been really hard to leave the start zone when i prestrafe it counts as if i was jumping inside (i guess) and locks my speed, I don't recall changing anything but I might have by mistake or my mate that also has access to the FTP it would be nice to have a feature that if you jump the timer would start even if you are jumping inside the start zone as soon as u lift ur feet of the startzone's floor the timer starts, would be dope! This is what happens
https://youtu.be/YknPnkNBL8A

**Comment by TotallyMehis** [comment]
https://influxtimer.com/download#faq the first one.

You can make the height of the start zone smaller. influx_zones_defzoneheight (height) will help.

**Comment by e-slut** [comment]
What SSJ plugin do you use?
