### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by e-slut** [TotallyMehis/Influx-Timer#30]
-Redesign the hud and add sync
-Showtriggers command
-Make it so we can have more timescale and edit speed options like blacky's TAS
-Fix timescale issue with CSGO
-Make it so you can drop your knife like on CSS instead of using !drop every time.
-Press E to replay bot
-Make it so when you finish a TAS you can go back and redo parts of the run.

Thank you Mehis for making such a great timer these are the only issues I have you're doing a great job.

**Comment by nknm** [comment]
You can drop the knife like cssm and showtriggers is a plugin you can get on AM!
