### ISSUE TITLE
Timescale

### ISSUE THREAD

**Issue by coffee12** [TotallyMehis/Influx-Timer#32]
the timescale does not work it shows 0.25 but is still at 1x speed i tried the command too and sm_tas_dectimescale
i tried the cl_clock_correction_force_server_tick/cl_clockdrift_max_ms 0

**Comment by nknm** [comment]
Im not a big tas use but i think it works on my server just a bit laggy but im unsure

**Comment by coffee12** [comment]
i changed the code so the plugin doesnt force timescale
