### ISSUE TITLE
Can't start runs

### ISSUE THREAD

**Issue by nknm** [TotallyMehis/Influx-Timer#34]
I first installed the new version of the timer and every run said "fps_max" so i proceeded to remove fps_check like always, then the time wouldn't start and it kept saying "[Influx] player_jump" and  "[Influx] You can't start this run!" I only removed fps_check and scroll/legit modes, i updated the csgo/addons/configs.

Edit: "[Influx] box character" new message
https://gyazo.com/abd00382f076bcecc9fb3b6f83a0e87b

**Comment by e-slut** [comment]
The error messages seem to be on how you leave zone zone if I leave the zone backwards I get the box character, if I try to prestrafe [Influx] nothing and if I use one key I get [Influx]You can't start this run!

**Comment by TotallyMehis** [comment]
You sure you removed influx_trikz? https://influxtimer.com/download#faq

**Comment by TotallyMehis** [comment]
You should try f51d3f49da18ca811b205c9ae6620425f30db681 which fixes the garbage string to find the underlying problem.

**Comment by e-slut** [comment]
We got it working it was trikz lol
