### ISSUE TITLE
Beams not showing

### ISSUE THREAD

**Issue by e-slut** [TotallyMehis/Influx-Timer#35]
I did everything that you said to do on the devlog I deleted influx_zones_beams_custom-plugin and updated influx_beams.cfg. Great work on the timer btw

EDIT:
Also not working on CSS. I do make all my zones full idk if that has anything to do with it. Going to try some other things.

EDIT2:
Got it working with a fresh install of sourcemod think it might be a plugin

**Comment by TotallyMehis** [comment]
This was caused by influx_beams.cfg not having the zone type color defined. It will now throw an error and use a default color instead of not displaying at all.

**Comment by e-slut** [comment]
Nice got it fixed. The zoning is being a bit weird now https://streamable.com/ocueq
