### ISSUE TITLE
New zoning is inaccurate and weird 

### ISSUE THREAD

**Issue by e-slut** [TotallyMehis/Influx-Timer#36]
https://streamable.com/ocueq

**Comment by TotallyMehis** [comment]
That's the new offset. b8a6887371a1b4056dc6ee83d6f2d745ebc511d1 fixes it.

**Comment by e-slut** [comment]
Thanks works perfectly now

**Comment by e-slut** [comment]
It's better but still happens
Edit:
https://streamable.com/he5bb
map bhop_chervona

**Comment by TotallyMehis** [comment]
Were there any errors?

**Comment by e-slut** [comment]
Nope

**Comment by e-slut** [comment]
It only does it with start and end zones. I tested it earlier and it seemed fine also I made sure I had the latest plugins from github

**Comment by nknm** [comment]
I cant see the white thingy anymore :(

**Comment by TotallyMehis** [comment]
Alright, try the newest version. It should solve the problem. You only need to update influx_zones-plugin.

**Comment by e-slut** [comment]
Works great now
