### ISSUE TITLE
Bug Zone_block.cfg Auto generated!

### ISSUE THREAD

**Issue by maugerb** [TotallyMehis/Influx-Timer#38]
One bug on auto generate Zone_block.cfg on Counter Strike Source!

The file is like:

// This file was auto-generated by SourceMod (v1.8.0.5951)
// ConVars for plugin "influx_zones_block.smx"

// Default punish type for block zones. (push, teletostart, disabletimer)
// -
// Default: "push"
influx_zones_block_punishtype "d

-----------------------------------------------------------------
-Error-
influx_zones_block_punishtype "d
-Good-
influx_zones_block_punishtype "disabletimer"

thx

**Comment by TotallyMehis** [comment]
This isn't the plugin's fault. I've now included the cfg in releases so SM doesn't have to auto-generate it. @ [influxtimer.com/download](http://influxtimer.com/download)

**Comment by maugerb** [comment]
Its good sorry! I downloaded 1 hour ago and the file Is not in!
