### ISSUE TITLE
Simpleranks

### ISSUE THREAD

**Issue by maugerb** [TotallyMehis/Influx-Timer#39]
When I finish a map 50% of time I got my new rank and points but its not show on de chat and I stay on my old rank! When I switch map I dont have my current rank (old rank) Not loaded correctly! I need to sm_rankmenu (Default rank) every map change. (counter strike source)!

thx you good job for lastestupdate! :)

**Comment by maugerb** [comment]
I think i need to have exact amount of poin to have the rank level up auto switch! Exemple I have 75 points next rank need 80 (I got 8 points to finish a map) = 83 points.

**Comment by maugerb** [comment]
And how to delete one replay? I have cheater to delete!

**Comment by ghost** [comment]
sm_deleterecording

**Comment by maugerb** [comment]
This command is not in the !help menu why?

**Comment by maugerb** [comment]
fix?

**Comment by TotallyMehis** [comment]
Yes, 901c3bfec1f5038befb8afc6ded1845ada8c7535 fixes it. Also, deleterecording is also now in the !help-menu.

**Comment by maugerb** [comment]
Great :) thx
