### ISSUE TITLE
Timer doesn't start with uncapped fps

### ISSUE THREAD

**Issue by wadeira** [TotallyMehis/Influx-Timer#4]
`fps_max 0` should make the fps uncapped, however, when we leave the start zone it will not start timer due to the fps being bellow the server tickrate / 300 fps lock

**Comment by TotallyMehis** [comment]
Good catch. I fixed it in 7e910aa520e22e706e4a03cb35c5b2f577531344 
You can download influx_fpscheck plugin from github and compile it. (note: requires include files)
