### ISSUE TITLE
Bonus

### ISSUE THREAD

**Issue by nknm** [TotallyMehis/Influx-Timer#40]
I've been playing a map with a bunch of bonuses and i noticed that when i finished like bonus #3 it sat the record for bonus #7 and #6, Also when i do !b it goes to b#7 and when i do !b1 also goes to b#7. If i only have one bonus its okay, everything works just fine. But its also kinda confusing, it would be great if the zones for the bonus would just be another color! (green-red = main, purple-yellow=Bonus for example)

**Comment by e-slut** [comment]
It goes to the last bonus whenever I do !b to. I wasn't able to recreate the issue where the record went to the wrong bonus I created 10 bonuses and finished them all seems to be working fine for me.

**Comment by TotallyMehis** [comment]
1532d14bfad5442b8d2142fe0aed9d1d358de8b7 should fix this.
