### ISSUE TITLE
Fix Menu?

### ISSUE THREAD

**Issue by Rostu13** [TotallyMehis/Influx-Timer#42]
Why menu = 
 modelen = 11, display = Half-Sideways id = 4 info = s4
 modelen = 11, display = Backwards id = 7 info = s7
 modelen = 11, display = Normal id = 0 info = s0
 modelen = 11, display = Low Gravity id = 6 info = s6
 modelen = 11, display = A/D-Only id = 3 info = s3
 modelen = 11, display = W-Only id = 2 info = s2
 modelen = 11, display = Real HSW id = 5 info = s5
 modelen = 11, display = Sideways id = 1 info = s1
 modelen = 11, display = Parkour id = 8 info = s8
 modelen = 11, display = Prespeed id = 10 info = s10
 modelen = 11, display = Tool Assisted id = 9 info = s9

but not
 modelen = 11, display = Normal id = 0 info = s0
 modelen = 11, display = Sideways id = 1 info = s1
 modelen = 11, display = W-Only id = 2 info = s2

And so on
![20170721211425_1](https://user-images.githubusercontent.com/22251516/28461394-c47a92c8-6e59-11e7-9f90-b3196c1efec0.jpg)
![20170721211422_1](https://user-images.githubusercontent.com/22251516/28461393-c479bb1e-6e59-11e7-959b-d7357a9a435c.jpg)
![20170721211424_1](https://user-images.githubusercontent.com/22251516/28461395-c48476e4-6e59-11e7-960f-bbb935ad5b17.jpg)

**Comment by TotallyMehis** [comment]
Are you talking about menu order? You can already change that with influx_style_overrides.cfg

**Comment by Rostu13** [comment]
Thx. Love you ^_^

**Comment by Rostu13** [comment]
@TotallyMehis how to fix zones menu? 
menu = 
![20170722161531_1](https://user-images.githubusercontent.com/22251516/28488930-23c0e71a-6ef9-11e7-8fad-7fdf63ce6ba8.jpg)
but not 1) Start Zone
2)End zone 
And so on

**Comment by e-slut** [comment]
Yeah, I do find that annoying especially on CSS the start and end zone options are on separate pages.

**Comment by TotallyMehis** [comment]
8c428bdec372e840c30b9e89df59a5730612bb08 should fix that.

**Comment by Rostu13** [comment]
@TotallyMehis Thx
