### ISSUE TITLE
TAS mouse positon isn't locked while paused

### ISSUE THREAD

**Issue by e-slut** [TotallyMehis/Influx-Timer#46]
https://streamable.com/6sctw

**Comment by TotallyMehis** [comment]
This was intentional. I can make an option to toggle it.

**Comment by e-slut** [comment]
Yeah do that, this can make the TAS look weird make it an option

**Comment by TotallyMehis** [comment]
cd9dcf9ee20419cb9d4c2101e60a15da57950571

**Comment by e-slut** [comment]
Thanks!
