### ISSUE TITLE
--->Suggestion<--- | Simple Rank

### ISSUE THREAD

**Issue by maugerb** [TotallyMehis/Influx-Timer#49]
Can you add option to finish multiple times a map and have point! Like first time you finish the map you have x point. When you finish again you have like %(cvar) of x point. (exemple 30%). Because on my server  all new player RTV every 5 min to earn point for rank. 

thx

**Comment by nknm** [comment]
Who actually cares about rank? XD
And if mehis does that then those guy's would play bhop_mp_stairs all day till they got infinite points.

**Comment by maugerb** [comment]
Yea but you can make 1000 point to rankup!
