### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by Rostu13** [TotallyMehis/Influx-Timer#5]
Why do not you want to stage, rank , WR , PB,  do in HUD? [Cs go]

**Comment by TotallyMehis** [comment]
You mean the sidebar?

Just the way I thought people would care about information. Stuff on the sidebar is misc info. The middle HUD is to show important info (time, speed, etc.)

**Comment by Rostu13** [comment]
Maybe it's really convenient. But also I think very convenient to add a buttons and sync in the HUD.
