### ISSUE TITLE
*Suggestion* Zones

### ISSUE THREAD

**Issue by nknm** [TotallyMehis/Influx-Timer#50]
Here is another suggestion about time glitching, there should be an option to start counting the time as soon as you jump instead of when you leave the start zone, that would allow pre-speed for noobs and would allow you to touch the start zone without resetting your timer by mistake in some maps, and even better it would cancer the time glitch!

**Comment by nknm** [comment]
Okay now its always saying " [Influx] You cannot jump at all at the start!" and cant start a run.

**Comment by e-slut** [comment]
Go to cfg/influx/prespeed.cfg and change influx_prespeed_maxjumps to -1. I had the same problem.
