### ISSUE TITLE
Never spawn with knife/weapon

### ISSUE THREAD

**Issue by M-archand** [TotallyMehis/Influx-Timer#55]
This started happening to me in more recent version of Influx, I'm using just the surf module for csgo. For some reason every time you join/rejoin the server you don't have a knife or pistol. Of course you could  use the wepgive commands but that's just a pain to use all the time. Is there a setting I'm missing somewhere, I combed but couldn't find anything? Or is it a bug? My `mp_ct_default_melee` & `mp_ct_default_secondary`	are all set properly.

**Comment by manchurii** [comment]
Is it on every map? because some surf maps remove weapons by default.

**Comment by M-archand** [comment]
Yes. I can unload all plugins & go on a surf map and have weapons, but once I enable Influx everything disappears.

**Comment by TotallyMehis** [comment]
Have you tried disabling influx_wepdrop? It's the only thing AFAIK that even touch removing weapons.

**Comment by M-archand** [comment]
Nah that doesn't do anything for me

**Comment by S4MT3K** [comment]
I know its a bit older... But did you guys figured out an solution? i really need help with this annoying thing... Dont want to type every single time  !drop" into the chat...
