### ISSUE TITLE
CSS: TAS Aim-Lock

### ISSUE THREAD

**Issue by e-slut** [TotallyMehis/Influx-Timer#58]
I made the same issue a long time ago, but it was only applied to CSGO not CSS.

**Comment by TotallyMehis** [comment]
Aim-lock does work with CSS. Is there something I'm missing?

**Comment by e-slut** [comment]
It doesn't show up in the menu I am running the latest dev branch version I tried generating new cvars, updating configs, etc.

**Comment by TotallyMehis** [comment]
Have you checked if you have influx_style_tas.smx? Because that's the old version.

**Comment by e-slut** [comment]
I did replace idk
