### ISSUE TITLE
Why are you using decl?

### ISSUE THREAD

**Issue by Lolztv12** [TotallyMehis/Influx-Timer#59]
Is there actually a reason for using this? You use the transitional syntax for nearly everything else.

```SourcePawn
    decl runid, irun, mode, style;
    decl String:szTime[10];
    decl String:szRun[MAX_RUN_NAME];
    decl String:szMode[MAX_MODE_NAME];
    decl String:szStyle[MAX_STYLE_NAME];
    decl String:szInfo[32];
    decl String:szDisplay[64];
    ArrayList rec;

**Comment by Zipcore** [comment]
decl char doesn't work yet, but in case you don't know why decl is used you should read this: https://wiki.alliedmods.net/Introduction_to_SourcePawn#decl

you don't benefit much from this, but in fact it is code optim
