### ISSUE TITLE
chat times

### ISSUE THREAD

**Issue by Hi-Ray** [TotallyMehis/Influx-Timer#6]
Hi anyway to swap the colors around for the chat to show ahead of time and behind 
like red for behind and green for ahead of time instead of green for behind and red for ahead its confusing players coming from ck

**Comment by TotallyMehis** [comment]
You can swap them around by changing these lines:
[influx_recchat.sp line 131](https://github.com/TotallyMehis/Influx-Timer/blob/master/addons/sourcemod/scripting/influx_recchat.sp#L131)
[influx_printcptimes.sp line 100](https://github.com/TotallyMehis/Influx-Timer/blob/master/addons/sourcemod/scripting/influx_printcptimes.sp#L100)

After that just recompile the plugins.
