### ISSUE TITLE
Chat triggers

### ISSUE THREAD

**Issue by iXyles** [TotallyMehis/Influx-Timer#60]
Hey, I wonder if its possible to maybe add a possibility to hide commands such as !r and also do so the admin chat is actually getting hidden, since when we write @ (in all / team) to write in the All chat or in the team admin chat, the chat trigger stills being displayed in the chat itself.

**Comment by TotallyMehis** [comment]
I recommend using SilentChatTrigger located in configs/core.cfg .

This does hide all !-commands but you can make a simple plugin to hide the commands you want.

**Comment by iXyles** [comment]
Well I've actually tried to look into it to resolve the issue, but since Influx handles the chat in some way around I cannot get it work with it.. therefore I asked if this is a possibility to resolve, the most important is the Admin chat. The "!r" chat trigger was just incased if it was possible in an easy matter :)

**Comment by TotallyMehis** [comment]
Influx isn't doing anything in that regard. You just have to set the SilentChatTrigger to ! only.
[This is an old plugin but this should work.](https://forums.alliedmods.net/showthread.php?p=508430)

**Comment by iXyles** [comment]
Well sadly to say it is "Influx" which is the problem in this matter when we're typing on all of our others servers with @ it doesn't show it in chat in neither all or team (all = (ALL SAY), team = admin chat in-game) - Same settings @ sourcemod.
I also have another plugin to detect "!calladmin" which does "return plugin_handled" which should make sure it's not being displayed in chat but it does IF include influx.

**Comment by xRz0** [comment]
add 

if ( IsChatTrigger ( ) ) return Plugin_Handled;

(around line 28) to influx_simpleranks_chat.sp and you should be fine

**Comment by iXyles** [comment]
Didnt have time to try this until tonight, worked as a charm cheers xRz0, doe I did only look at certain "commands" and not all chattriggers :)

**Comment by strafe** [comment]
@xRz0 what's your Steam?
