### ISSUE TITLE
Simpleranks - preference?

### ISSUE THREAD

**Issue by iXyles** [TotallyMehis/Influx-Timer#63]
Bug : You're not getting points if you completed the map a second time as intended
Solution : Row 128 in influx_simpleranks/db_cp.sp - should be break and not return.

**Comment by TotallyMehis** [comment]
But it isn't intended? That line makes sure you don't get awarded more than once for the same mode & style. It'll only award you if the reward has been increased.

**Comment by iXyles** [comment]
Hmm okay, I see, well in our case we changed this to the opposite since it feels like a player should be rewarded to continue play on the server itself and gain ranks/points from it depending on which mode/style the user plays.
Feels like its a personal preference for the server owner I suspect then.

**Comment by iXyles** [comment]
After some thinking I do understand the design choice in that, would it be possible to redesign it so the server owner could decide themself how it should be with an ease?
