### ISSUE TITLE
Player ladder

### ISSUE THREAD

**Issue by alerad** [TotallyMehis/Influx-Timer#7]
Hey, i've been checking out this plugin and I want to discard my ckSurf version for this. However, i see there's no player ladder at the moment, do you have any progress on that?

If you don't, i'll start coding it, but we could exchange ideas on which approach to take on that.

I added you to steam in case you want to further discuss this. (Ayeayeaye)

**Comment by TotallyMehis** [comment]
Nothing is being developed behind the curtains. Feel free to make a pull request!
Try to keep it in its own separate plugin.

I accepted your request on Steam. Keep the ideas here so others can comment on them.

**Comment by alerad** [comment]
Yeah, i'm not planning on ruining this project's structure :)

Will brainstorm a bit on how to do this.

**Comment by alerad** [comment]
Hey, i've been thinking a bit about it and decided to use KSF's ranking system (A bit modified though).

You would be able to configure it with a KV file like this.
```
"Configurations"
{
	"Groups"
	{
		“Group 1”
		{
			“percentile”  “0.5”
		}
		“Group 2”
		{
			“percentile” “5”
			"pointmodifier" "2"
		}
		“Group 3”
		{
			“percentile” “15”
			"pointmodifier" "4"
		}
	}
	"Points"
	{
		"Stage"
		{
			"basepoints" "0"
		}
		"Bonus"
		{
			"basepoints" "250"
		}
		"Map"
		{
			"basepoints" "800"
		}
	}
	"TopPositionsExtraPoints"
	{
		"Stage"
		{
		} 
		"Map"
		{
			"1"	"200"
			"2"	"100"
			"3"	"50"
			"4"	"25"
			"5"	"10"
		}
		"Bonus"
		{

		}
	}
}


```

The pointmodifier property would divide the run basepoints by it. For example, for group 2 it would be 400 points (basepoints/2)

The percentile property would mean on what top % of a map you need to be for the group points to be applied.

The TopPositionsExtraPoints section would give extra points according to rank.

What do you think about it? Would you change something?

**Comment by rambatencs** [comment]
Is there coming possible ranking soon for this timer?

**Comment by SeatloN** [comment]
Well what i can see with this plugin right now is that the only thing i don't have that players on my server are asking for is Server rank function like on CKsurf or Simulare plugins. 

Using map ranking from plugin 

and adding server ranking like on the web-panel

Think what alerad said by using a point system like CKsurf and Kztimer is quite useful because people are use to that system. Another system i know people are discussing are XP based ( More like loyalty system )
