### ISSUE TITLE
Time scale not reset when change mode when use tas style

### ISSUE THREAD

**Issue by rsgua** [TotallyMehis/Influx-Timer#71]
Time scale not reset when change mode when use tas style.
When i set timescale in tas menu on 0.1 and change mod in style menu then reset time and so on but timescale not reset and i see in tas menu time scale 0.1 but i can go normal in normal time scale but time in timer work like timescale 0.1.

**Comment by TotallyMehis** [comment]
This is intended. Use influx_modeactstyle 1.

**Comment by rsgua** [comment]
its not good i can`t use scroll and tas and so on!
I think you must make reset!

**Comment by TotallyMehis** [comment]
If I understood your problem right, try [this](https://www.dropbox.com/s/c9lk49svohju0mv/taspluginsfix.zip?dl=0).

**Comment by e-slut** [comment]
I think he means to make tas a mode instead of a style?

**Comment by rsgua** [comment]
my fix for this problem
Influx_OnClientModeChangePost -> if style not tas - return -> SetTimescale 1.0
mehis, and i don`t try test your fix...
