### ISSUE TITLE
Segmenting?

### ISSUE THREAD

**Issue by orangepin19** [TotallyMehis/Influx-Timer#74]
Is there a feature that lets me zone multiple checkpoints that fall under one "run", so that if I complete the map using those checkpoints it has it's own replay?

I've completed a map using the !practice mode with several checkpoints but I'd like to be able to see the full run segmented together. The zone "checkpoint" doesn't seem to work the way I expected it to, but maybe there's something I'm overlooking?

**Comment by TotallyMehis** [comment]
There is no replay for practice runs. Use TAS, it's basically the same thing anyway.
