### ISSUE TITLE
This Plugin can support trikz?

### ISSUE THREAD

**Issue by Power28** [TotallyMehis/Influx-Timer#75]
This timer is my favorite one. but i'm a trikz player if i use this plugin for trikz. can it work?

**Comment by TotallyMehis** [comment]
Semi-supported https://github.com/TotallyMehis/Influx-Timer/tree/trikz

**Comment by Power28** [comment]
very thx your response but i have some problem with flash explosion. wish one day can perfectly support. thanks a lot
