### ISSUE TITLE
Some erros and timer cant finished

### ISSUE THREAD

**Issue by TonkiTon** [TotallyMehis/Influx-Timer#78]
Good day.

It seems that something has broken after the cs go update.
Because literally yesterday everything was good and worked perfectly.
But today...

1) timer does not stop at the finish
and I get in the moment when I touch the finish zone such an error

```[influx_core.smx] [Influx] Client 'Tonki_Ton' has no mode! Cannot finish timer.```

2) Checkpoints.

When you touch the checkpoint zone in the log a error is written

```
[SM] Exception reported: Invalid block -468 (blocksize: 4979)
[SM] Blaming: influx_zones_checkpoint.smx
[SM] Call stack trace:
[SM]   [0] ArrayList.Get
[SM]   [1] Line 973, D:\Контент\1.8 compiler\addons\sourcemod\scripting\influx_zones_checkpoint.sp::GetClientCPTime
[SM]   [2] Line 729, D:\Контент\1.8 compiler\addons\sourcemod\scripting\influx_zones_checkpoint.sp::SaveClientCP
[SM]   [3] Line 1148, D:\Контент\1.8 compiler\addons\sourcemod\scripting\influx_zones_checkpoint.sp::Native_SaveClientCP
[SM]   [5] Influx_SaveClientCP
[SM]   [6] Line 577, D:\Контент\1.8 compiler\addons\sourcemod\scripting\influx_zones_stage.sp::E_StartTouchPost_Stage
```

And with all this I will immediately say that over the past day I have not made any changes, in general.

**Comment by TotallyMehis** [comment]
Can you make sure all plugins are running correctly ('sm plugins list' in server console)
