### ISSUE TITLE
sm_customrank and Admin tag

### ISSUE THREAD

**Issue by Cruze03** [TotallyMehis/Influx-Timer#81]
1) Can someone tell me how do I reset custom rank (like remove customrank and return to points rank system)

2) How do I enable admin tags which is already given in plugin (Admin, Super Admin and Root)

3) Can you add a command "sm_back" which teleports you to the start of the STAGE not Mapstart like cksurf has.

Thanks for helping me in advance ^^

**Comment by TotallyMehis** [comment]
!rankmenu

Make sure your admin flags are correct.

**Comment by Cruze03** [comment]
and can we make that when we have points for certain rank, it automatically gives rank instead of buying it in !rankmenu

btw, thanks !rankmenu working =)

**Comment by TotallyMehis** [comment]
Ranks already have functionality by default. You can turn it OFF with "unlock" "1"

**Comment by Cruze03** [comment]
yeah, my bad. thanks ^^

**Comment by Cruze03** [comment]
last things (probably)
1) there is no tele-to-start zone? like I dont want people go in map's jail..So I was thinking if there is a zone that teleports you to start
2) what does teleport and validator zone do exactly??
Thanks for your time ^^

**Comment by Cruze03** [comment]
I did point 1 with Francisco's dev zones..

**Comment by TotallyMehis** [comment]
Use block zone

**Comment by Cruze03** [comment]
It just tells "You shouldn't be here" doesn't teleports you. Most people don't know you have to type !r to restart so they then dc..anyway I used dev zones so it's fine now

**Comment by TotallyMehis** [comment]
Change behavior through the zone settings.

**Comment by Cruze03** [comment]
Thanks!! and sorry, didn't notice that.
So let's close this issue :)
