### ISSUE TITLE
problem with bhop_exodus_fix

### ISSUE THREAD

**Issue by hernancussit** [TotallyMehis/Influx-Timer#83]
When I try to load the map with the timer, the server goes into the restart loop. If I take out the timer it works fine
SM PLUGINS LIST

> [SM] Listing 97 plugins:
>            01 "Admin File Reader" (1.8.0.6041) by AlliedModders LLC
>            02 "Basic Chat" (1.8.0.6041) by AlliedModders LLC
>            03 "Admin Menu" (1.8.0.6041) by AlliedModders LLC
>            04 "Basic Comm Control" (1.8.0.6041) by AlliedModders LLC
>            05 "Anti-Flood" (1.8.0.6041) by AlliedModders LLC
>            06 "Basic Commands" (1.8.0.6041) by AlliedModders LLC
>            07 "Basic Info Triggers" (1.8.0.6041) by AlliedModders LLC
>            08 "Basic Votes" (1.8.0.6041) by AlliedModders LLC
>            09 "Client Preferences" (1.8.0.6041) by AlliedModders LLC
>            10 "Fun Commands" (1.8.0.6041) by AlliedModders LLC
>            11 "Fun Votes" (1.8.0.6041) by AlliedModders LLC
>            12 "Player Commands" (1.8.0.6041) by AlliedModders LLC
>            13 "Reserved Slots" (1.8.0.6041) by AlliedModders LLC
>            14 "Sound Commands" (1.8.0.6041) by AlliedModders LLC
>            15 "Admin Help" (1.8.0.6041) by AlliedModders LLC
>            16 "SourceBans++: SourceComms" (1.6.2) by Alex, SourceBans++ Dev Team
>            17 "SourceBans++: SourceSleuth" (1.6.2) by ecca, SourceBans++ Dev Team
>            18 "SourceBans++: Admin Config Loader" (1.6.2) by AlliedModders LLC, SourceBans++ Dev Team
>            19 "SourceBans++: Bans Checker" (1.6.2) by psychonic, Ca$h Munny, SourceBans++ Dev Team
>            20 "SourceBans++: Main Plugin" (1.6.2) by SourceBans Development Team, SourceBans++ Dev Team
>            21 "Influx - Disable Radio" (1.2) by Mehis
>            22 "Influx - Block +left/+right" (1.2) by Mehis
>            23 "Influx - Drop Knife" (1.2) by Mehis
>            24 "Influx - Disable Suicide" (1.2) by Mehis
>            25 "Influx - Config" (1.2) by Mehis
>            26 "Influx - Core" (1.2) by Mehis
>            27 <Failed> "Influx - Compatibility | Standup" (1.1.1 Hotfix) by Mehis
>            28 "Influx - Fix Timelimit" (1.2) by Mehis
>            29 "Influx - FPS Check" (1.2) by Mehis
>            30 "Influx - HUD" (1.2) by Mehis
>            31 "Influx - Help" (1.2) by Mehis
>            32 "Influx - HUD Draw" (1.2) by Mehis
>            33 "Influx - HUD | Draw CSS" (1.2) by Mehis
>            34 Disabled: "Influx - HUD Draw | CS:GO" (1.2) by Mehis
>            35 "Influx - HUD | Hide HUD" (1.2) by Mehis
>            36 "Influx - HUD | Hide Players" (1.2) by Mehis
>            37 "Influx - HUD | Chat Records" (1.2) by Mehis
>            38 "Influx - HUD | Record Sounds" (1.2) by Mehis
>            39 "Influx - Hide Players | Weapon Sounds" (1.2) by Mehis
>            40 "Influx - Jumps" (1.2) by Mehis
>            41 "Influx - HUD | Viewmodel" (1.2) by Mehis
>            42 "Influx - Map Rankings" (1.2) by Mehis
>            43 <Failed> "Influx - Mode - Auto" (1.2) by Mehis
>            44 "Influx - Mode - Auto" (1.2) by Mehis
>            45 "Influx - Mode - Stock Cap" (1.2) by Mehis
>            46 "Influx - Mode - Scroll" (1.2) by Mehis
>            47 "Influx - Noclip" (1.2) by Mehis
>            48 "Influx - No Damage" (1.2) by Mehis
>            49 "Influx - No Collision" (1.2) by Mehis
>            50 "Influx - Mode - VelCap" (1.2) by Mehis
>            51 "Influx - Pause" (1.2) by Mehis
>            52 "Influx - Practice" (1.2) by Mehis
>            53 "Influx - Prespeed" (1.2) by Mehis
>            54 "Influx - Chat Records" (1.2) by Mehis
>            55 "Influx - Print CP Times" (1.2) by Mehis
>            56 "Influx - Recording" (1.2) by Mehis
>            57 "Influx - Records Menu" (1.2) by Mehis
>            58 "Influx - Record Sounds" (1.2) by Mehis
>            59 "Influx - Record Rank" (1.2) by Mehis
>            60 "Influx - Simple Ranks | Chat" (1.2) by Mehis
>            61 "Influx - Spectator All Talk (CSS)" (1.2) by Mehis
>            62 "Influx - Simple Ranks" (1.2) by Mehis
>            63 "Influx - Strafe Sync" (1.2) by Mehis
>            64 "Influx - Strafes" (1.2) by Mehis
>            65 "Influx - Style - A/D-Only" (1.2) by Mehis
>            66 "Influx - Style - Half-Sideways" (1.2) by Mehis
>            67 "Influx - Style - Backwards" (1.2) by Mehis
>            68 "Influx - Style - Prespeed" (1.2) by Mehis
>            69 "Influx - Style - Normal" (1.2) by Mehis
>            70 "Influx - Style - Parkour" (1.2) by Mehis
>            71 "Influx - Style - Sideways" (1.2) by Mehis
>            72 Disabled: "Influx - Style - TAS" (1.2) by Mehis
>            73 "Influx - Spectator List" (1.2) by Mehis
>            74 "Influx - Style - TAS" (1.2) by Mehis
>            75 "Influx - Style - W-Only" (1.2) by Mehis
>            76 "Influx - Teams" (1.2) by Mehis
>            77 "Influx - Autojoin Team" (1.2) by Mehis
>            78 "Influx - Teleport to end" (1.2) by Mehis
>            79 "Influx - Style - Real Half-Sideways" (1.2) by Mehis
>            80 "Influx - Teleport To Run" (1.2) by Mehis
>            81 "Influx - True Velocity" (1.2) by Mehis
>            82 "Influx - Weapon Drop" (1.2) by Mehis
>            83 "Influx - Zones" (1.2) by Mehis
>            84 "Influx - Give Weapons" (1.2) by Mehis
>            85 "Influx - Style - Low Gravity" (1.2) by Mehis
>            86 "Influx - Zones | Block" (1.2) by Mehis
>            87 "Influx - Zones | Beams" (1.2) by Mehis
>            88 "Influx - Zones | Checkpoint" (1.2) by Mehis
>            89 "Influx - Zones | Autobhop" (1.2) by Mehis
>            90 "Influx - Zones | Freestyle" (1.2) by Mehis
>            91 "Influx - Zones | Stage" (1.2) by Mehis
>            92 "Influx - Zones | Teleport" (1.2) by Mehis
>            93 "Influx - Zones | Validator" (1.2) by Mehis
>            94 "Influx - Zones | Timer" (1.2) by Mehis
>            95 "Multiplayer Bunnyhops: Source" (1.0.0.4) by DaFox & petsku
>            96 "Welcome Sound" (0.0.1) by R-Hehl
>            97 "Nextmap" (1.8.0.6041) by AlliedModders LLC
>          Errors:
>          influx_comp_standup.smx (Influx - Compatibility | Standup): Could not find required plugin "standup_core"
>          influx_mode_auto_csgo.smx (Influx - Mode - Auto): Bad engine version!
>

**Comment by TotallyMehis** [comment]
Do you have a nav file? Have you tried just unloading influx_recording?

**Comment by hernancussit** [comment]
I have generated the .nav file through the recommended plugin and manually inside the server. In both cases the server goes in the loop. If I disable the plugin influx_recording works fine.
Is there any way to fix the error?

**Comment by TotallyMehis** [comment]
Have you tried manually adding a bot with bot_quota 1?

**Comment by hernancussit** [comment]
with bot_quota 1 is the same, it still does not work
