### ISSUE TITLE
How to delete record?

### ISSUE THREAD

**Issue by backedelk031** [TotallyMehis/Influx-Timer#84]
How to delete only one record not full category?
Influx 1.2

**Comment by TotallyMehis** [comment]
You open the record with !wr or similar command and press delete record.

**Comment by backedelk031** [comment]
But i dont have "Delete record" i have only "Checkpoints record" with full admin

**Comment by backedelk031** [comment]
![image](https://user-images.githubusercontent.com/36257134/41271429-0d2f48ee-6e2a-11e8-812d-9c5952954e76.png)

**Comment by TotallyMehis** [comment]
Have you overridden sm_inf_removerecords flags through admin_overrides.cfg? By default you need z (root).

**Comment by backedelk031** [comment]
I override it on default
![image](https://user-images.githubusercontent.com/36257134/41290807-61d0b936-6e67-11e8-90c3-1635d867c4b5.png)

**Comment by TotallyMehis** [comment]
And YOU also have the Z-flag? Try removing the override.

**Comment by backedelk031** [comment]
Yea, i have Z flag. I add this override because "delete record" nor working.

**Comment by TotallyMehis** [comment]
Are you 100% sure you have the z-flag? Check with sm_who console command.

**Comment by backedelk031** [comment]
Yes i sure.
] sm_who Vital
[SM] "Vital" имеет доступ: root

**Comment by backedelk031** [comment]
I just dont update influx_core from 1.1.1 to 1.2
