### ISSUE TITLE
Prespeed

### ISSUE THREAD

**Issue by obivan43** [TotallyMehis/Influx-Timer#85]
Hi I got prespeed problem on my dedicated server, without weapon always 260 in csgo with prespeed should be ~285 can you explain why ?

**Comment by TotallyMehis** [comment]
You need the [CS:GO movement unlocker](https://forums.alliedmods.net/showthread.php?t=255298) and proper cvars:
```
sv_friction 4
sv_stopspeed 100
sv_accelerate 5
```

If you have further questions, please use the [Discord server](https://discord.gg/Mc5VDQT).
