### ISSUE TITLE
Error with MYSQL query

### ISSUE THREAD

**Issue by bruno-args** [TotallyMehis/Influx-Timer#86]
Hello, i have problem with ranks and wr menu. I can't open wr menu in chat : (something went wrong), and log looks like this:

`[influx_recordsmenu.smx] [Influx] SQL Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'rank FROM inf_times AS _t INNER JOIN inf_users AS _u ON _t.uid=_u.uid INNER JOIN' at line 1 (printing records to client)`

Also, ranks at finish say : Couldn't retrieve your ranks! Please try reconnecting, and log looks like this:

`influx_maprankings.smx] [Influx] SQL Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'rank FROM inf_times AS _t WHERE uid=1 AND mapid=1 AND runid=1 AND mode=1 AND sty' at line 1 (getting client ranks)`

Thanks in advance.

**Comment by TotallyMehis** [comment]
What version of MySQL are you using?

**Comment by bruno-args** [comment]
Hey Mehis, MySQL 8.0

**Comment by TotallyMehis** [comment]
Thanks for reporting the issue. [Try using these modified versions](https://www.dropbox.com/s/z7d8nxvwln2j452/recordsmenu_maprankings.zip?dl=0).

**Comment by bruno-args** [comment]
Thanks Mehis. Issue are gone.
