### ISSUE TITLE
[QUES] prev_pb and prev_best

### ISSUE THREAD

**Issue by Cruze03** [TotallyMehis/Influx-Timer#89]
Influx_OnTimerFinishPost(int client, int runid, int mode, int style, float time, float prev_pb, float prev_best, int flags);

I am confused on what is the difference between "prev_pb" and "prev_best" in this forward?
Can you also please tell me the types of "mode"?
Thanks in advance ^^

**Comment by TotallyMehis** [comment]
prev_pb = client's previous best
prev_best = mode, style combo previous best (ie. server record)
mode = scroll, auto, etc. (see influx_mode_*.smx) styles are a sub-set, so you can have scroll w-only and auto w-only.

**Comment by Cruze03** [comment]
Thanks and sorry for replying to this so late ._.
