### ISSUE TITLE
Some errors with dev branch

### ISSUE THREAD

**Issue by bruno-args** [TotallyMehis/Influx-Timer#90]
Hello. In dev build i found some errors.

- After set up start/end and finish - all fine, replay is work and zones too.
But if you restart/change current map, all zones are gone, replaybot fly away (yeah, that really funny, replaybot just fly in the sky). Also all information about records fly away from hud too, only if you will write !wr, you can see wr's.
 I see you remake zones plugin, and now all zones write into DB, not in files, so, next error is:

```
"1"	"1"	"""""\""\\\""\\\\\\\""\\\\\\\\\\\\\\\""\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\""\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"
"1"	"2"	"""""\""\\\""\\\\\\\""\\\\\\\\\\\\\\\""\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\""\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"
```

This is dump of inf_zones table. I guess, this is not normal.

Well, i hope you will fix that. Thanks for updates and support of timer.

**Comment by TotallyMehis** [comment]
Thanks for reporting this. I assume you're using MySQL, which I haven't tested yet. I suggest you go back to build 13.

**Comment by TotallyMehis** [comment]
Try latest dev build.

**Comment by pawnlab** [comment]
Took latest build (10 min ago). Tested, works fine. Thanks mate. If i found something else, i will inform.

**Comment by bruno-args** [comment]
Took latest build (30 min ago). Tested, zones are loading, replaybot (when we call !replay, play properly records). In table inf_runs all fine, telepos and other are write normally. In inf_zones now blank table, but zones are draw, like i said, and work fine. Thanks!
