### ISSUE TITLE
influx_recording.smx handles to high (Memory Leak)?

### ISSUE THREAD

**Issue by freakexeuLow** [TotallyMehis/Influx-Timer#94]
Hey Mehis, i have a lot of handles with this plugin, is this normal?

Owner | Handles | Memory
-- | -- | --
influx_recording.smx | 1751 | 740068 bytes

**Comment by RyamosThomas** [comment]
Prestrafe recording clones an arraylist and doesn't properly close it. Disabling that should reduce the memory leaks.

**Comment by freakexeuLow** [comment]
> Prestrafe recording clones an arraylist and doesn't properly close it. Disabling that should reduce the memory leaks.

Ohh hey Kid, But the Replay Bot won't work after that, will it?

**Comment by TotallyMehis** [comment]
> 
> 
> Hey Mehis, i have a lot of handles with this plugin, is this normal?
> Owner 	Handles 	Memory
> influx_recording.smx 	1751 	740068 bytes

That does not look normal. I think I've spotted the issue. Expect a fix soon.

**Comment by TotallyMehis** [comment]
Try using the dev version of influx_recording.

**Comment by freakexeuLow** [comment]
Thanks Mehis, problem is gone

**Comment by freakexeuLow** [comment]
@TotallyMehis 

It hasn't gotten any better its now over 31 million leaks (picture below)
https://i.imgur.com/j3zHEV5.png

**Comment by TotallyMehis** [comment]
Is that from a map with a lot of long recordings? 88 handles is reasonable.

- 65 pre-run recordings
- Any active runners
- Any record bot recordings.

**Comment by freakexeuLow** [comment]
I have other 200 maps on the server so the handles are not the problem, so i mean the leaks are over 31 million. I don't think that's normal.

**Comment by TotallyMehis** [comment]
You didn't answer my question. Does the map, in which you used the command to show the handle info, have long recordings? If there was a leak, the handle number would go up.

**Comment by freakexeuLow** [comment]
Oh Sorry and I've completely evaluated this. So this is the site here: https://snksrv.com/tools/sourcemod/handles-analyzer.html

Here is my dumb: https://pastebin.com/0XCtytQK

So I don't think he specifically picks a map in this^^

**Comment by TotallyMehis** [comment]
That looks normal. You have 65 smaller pre-run recordings and a few larger ones that look like they are record recordings. You can change the max recording length to bring the memory usage down.

**Comment by freakexeuLow** [comment]
mhh you mean this here?
// Max recording length in minutes.
// -
// Default: "75"
influx_recording_maxlength "75"

**Comment by TotallyMehis** [comment]
Yea
