### ISSUE TITLE
SQL secure querys

### ISSUE THREAD

**Issue by ghost** [TotallyMehis/Influx-Timer#98]
Right now, the InfluxTimer sucks if I use special characters in the request. You should format the request before sending it (SQL_FormatQuery).

@TotallyMehis This is a critical bug

> 
L 03/04/2020 - 20:32:44: [influx_core.smx] [Influx] SQL Error: Query execution was interrupted (getting best records)
L 03/04/2020 - 20:33:04: [influx_core.smx] [Influx] SQL Error: Query execution was interrupted (getting best records)
L 03/04/2020 - 20:33:44: [influx_maprankings.smx] [Influx] SQL Error: Query execution was interrupted (getting record count)
L 03/04/2020 - 20:34:04: [influx_recordsmenu.smx] [Influx] SQL Error: Query execution was interrupted (printing records menu, style select to client)

**Comment by TotallyMehis** [comment]
I'll get to fixing this and some of the other bugs as soon as I have some time.

**Comment by TotallyMehis** [comment]
Please try out the latest dev release.
While I haven't encountered the problem myself yet, I increased the buffer size and wrapped the name and map searching with SQL_EscapeString.

**Comment by ghost** [comment]
well, I'll check it soon.
It would be nice if you wrap all requests with this function.

**Comment by ghost** [comment]
I noticed that the error occurs when trying to read/write players with special characters such as smilies or any another dumbest symbols in username

**Comment by TotallyMehis** [comment]
@Nullent try now. You may need to change the character set and collation to utfmb4 for the inf_users table.
ie:
```sql
ALTER TABLE inf_users CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```

**Comment by ghost** [comment]
thx, problem resolved
